version: 0.2

phases:
  #install:
    # runtime-versions:
    #   name: version
      # name: version
    #commands:
      # - command
      # - command
  pre_build:
    commands:
       - docker build -t sahil91096/dev-client -f ./client/Dockerfile.dev ./client
  build:
    commands:
      - docker run -e CI=true sahil91096/dev-client npm test
  post_build:
    commands:
      - docker build -t sahil91096/worker ./worker
      - docker build -t sahil91096/server ./server
      - docker build -t sahil91096/client ./client
      - docker build -t sahil91096/nginx ./nginx
      ##### Fetching credentials from parameter store to login into dockerhub ###
      - access_token=$(aws ssm get-parameter --name "docker_hub_access_token" --query "Parameter.Value" --output text)
      - user_name=$(aws ssm get-parameter --name "user_name_docker_hub" --query "Parameter.Value" --output text)
      ##### Login to docker hub####
      - echo "$access_token" | docker login -u $user_name --password-stdin
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
