version: 0.2

phases:
  #install:
    # runtime-versions:
    #   name: version
      # name: version
    #commands:
      # - command
      # - command
  pre_build:
    commands:
       - docker build -t sahil91096/dev-client -f Dockerfile.dev ./client
  build:
    commands:
      - docker run -e CI=true sahil91096/dev-client npm test
  post_build:
    commands:
      - docker build -t sahil91096/worker ./worker
      - docker build -t sahil91096/server ./server
      - docker build -t sahil91096/client ./client
      - docker build -t sahil91096/nginx ./nginx
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
